/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xlive_client_XmppClient */

#ifndef _Included_com_xlive_client_XmppClient
#define _Included_com_xlive_client_XmppClient
#ifdef __cplusplus
extern "C" {
#endif
#undef com_xlive_client_XmppClient_RegistrationSuccess
#define com_xlive_client_XmppClient_RegistrationSuccess 0L
#undef com_xlive_client_XmppClient_RegistrationNotAccetable
#define com_xlive_client_XmppClient_RegistrationNotAccetable 1L
#undef com_xlive_client_XmppClient_RegistrationConflict
#define com_xlive_client_XmppClient_RegistrationConflict 2L
#undef com_xlive_client_XmppClient_RegistrationNOTAUTHORIZED
#define com_xlive_client_XmppClient_RegistrationNOTAUTHORIZED 3L
#undef com_xlive_client_XmppClient_RegistrationBadRequest
#define com_xlive_client_XmppClient_RegistrationBadRequest 4L
#undef com_xlive_client_XmppClient_RegistrationForbidden
#define com_xlive_client_XmppClient_RegistrationForbidden 5L
#undef com_xlive_client_XmppClient_RegistrationRequired
#define com_xlive_client_XmppClient_RegistrationRequired 6L
#undef com_xlive_client_XmppClient_RegistrationUnexpectedRequest
#define com_xlive_client_XmppClient_RegistrationUnexpectedRequest 7L
#undef com_xlive_client_XmppClient_RegistrationNotAllowed
#define com_xlive_client_XmppClient_RegistrationNotAllowed 8L
/*
 * Class:     com_xlive_client_XmppClient
 * Method:    register_user
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xlive_client_XmppClient_register_1user
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_xlive_client_XmppClient
 * Method:    send_xmpp_info
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IZ)I
 */
JNIEXPORT void JNICALL Java_com_xlive_client_XmppClient_send_1xmpp_1info
  (JNIEnv *, jclass, jstring, jstring, jstring, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
